MAX_JUMP_TIME = 0.12
HIT_PARALIZE_TIME = 0.2

JUMPING_FORCE = -100000
RUNNING_FORCE = 30000
WALKING_FORCE = 3000

JUMP = ' '
MOVE_RIGHT = 'right'
MOVE_LEFT = 'left'
WALK = 'walk'
RIDE = 'ride'

PLAYER_APPLIED_FORCES = {JUMP = JUMP, MOVE_RIGHT = MOVE_RIGHT, MOVE_LEFT = MOVE_LEFT}

FORCES =
{
	JUMP = {x = 0, y = JUMPING_FORCE},
	MOVE_RIGHT = {x = RUNNING_FORCE, y = 0},
	MOVE_LEFT = {x = -RUNNING_FORCE, y = 0},
	WALK = {x = WALKING_FORCE, y = 0},
	RIDE = {x = WALKING_FORCE, y = 0}
}

AIR_FRICTION = 0.9
SURFACE_FRICTION = 0.6

DIRECTION = {RIGHT = 1, LEFT = -1}