MAX_JUMP_TIME = 0.12
HIT_PARALIZE_TIME = 0.2

JUMPING_FORCE = -100000
RUNNING_FORCE = 30000
WALKING_FORCE = 3000

JUMP = ' '
MOVE_RIGHT = 'right'
MOVE_LEFT = 'left'
WALK = 'walk'
RIDE = 'ride'

PLAYER_APPLIED_FORCES = {JUMP = JUMP, MOVE_RIGHT = MOVE_RIGHT, MOVE_LEFT = MOVE_LEFT}

FORCES =
{
	JUMP = vector.new(0, JUMPING_FORCE),
	MOVE_RIGHT = vector.new(RUNNING_FORCE, 0),
	MOVE_LEFT = vector.new(-RUNNING_FORCE, 0),
	WALK = vector.new(WALKING_FORCE, 0),
	RIDE = vector.new(WALKING_FORCE, 0)
}

SURFACE_FRICTION = 0.6

DIRECTION = {RIGHT = 1, LEFT = -1}